# .github/workflows/main.yml
name: 'Build & Tests'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#  schedule:
#    - cron: '5 5 * * 5'
   
jobs:
  
  macOS-build:
    runs-on: macos-14
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Select Xcode 15.4
      run: sudo xcode-select -s "/Applications/Xcode_15.4.app"
    - uses: mxcl/xcodebuild@v3.3
      with:
        platform: macOS
        scheme: 'PerseusGeoLocationKit'
        action: build
        code-coverage: true
        verbosity: xcpretty
        upload-logs: always
        
  macOS-test:
    runs-on: macos-14
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Select Xcode 15.4
      run: sudo xcode-select -s "/Applications/Xcode_15.4.app"
    - uses: mxcl/xcodebuild@v3.3
      with:
        platform: macOS
        scheme: 'PerseusGeoLocationKit'
        action: test
        code-coverage: true
        verbosity: xcpretty
        upload-logs: always
