# .github/workflows/main.yml
name: 'Build & Tests'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#  schedule:
#    - cron: '5 5 * * 5'

jobs:

  macOS-build:
    runs-on: macos-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
#    - name: Select Xcode 16.2
#      run: sudo xcode-select -s "/Applications/Xcode_16.2.app"
    - uses: mxcl/xcodebuild@v3
      with:
        platform: macOS
        scheme: 'PerseusGeoKit'
        action: build
        code-coverage: true
        verbosity: xcpretty
        upload-logs: always

  macOS-test:
    runs-on: macos-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
#    - name: Select Xcode 16.2
#      run: sudo xcode-select -s "/Applications/Xcode_16.2.app"
    - uses: mxcl/xcodebuild@v3
      with:
        platform: macOS
        scheme: 'PerseusGeoKit'
        action: test
        code-coverage: true
        verbosity: xcpretty
        upload-logs: always

  iOS-build:
    runs-on: macos-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
#    - name: Select Xcode 16.2
#      run: sudo xcode-select -s "/Applications/Xcode_16.2.app"
    - uses: mxcl/xcodebuild@v3
      with:
        platform: iOS
        scheme: 'PerseusGeoKit'
        action: build
        code-coverage: true
        verbosity: xcpretty
        upload-logs: always

  iOS-test:
    runs-on: macos-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
#    - name: Select Xcode 16.2
#      run: sudo xcode-select -s "/Applications/Xcode_16.2.app"
    - uses: mxcl/xcodebuild@v3
      with:
        platform: iOS
        scheme: 'PerseusGeoKit'
        action: test
        code-coverage: true
        verbosity: xcpretty
        upload-logs: always
